[project]
name = "cu_agent1"
version = "0.1.0"
description = "cu_agent1 using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.102.0,<1.0.0",
]

[project.scripts]
kickoff = "cu_agent1.main:kickoff"
plot = "cu_agent1.main:plot"
cu = "cu_agent1.hello:run_custom_flow"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
